version: '3.5'

services:
        mongo:
            container_name: mongoDatabase
            image: mongo
            volumes:
                - ./mongodb-data:/var/lib/mongodb/data
            ports: 
                - 27000:27017