import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

//Usar Link en vez de <a> para que evitar recarga completa de la pagina, solo ese componente

export default function Home( { listadoProyectos } ) {

  /*this.listadoProyectosHTML = listadoProyectos.proyectos.map((item, index) => 
    <li className="lambda" key={item.id}>{item.name}
      <button>
        supprimer cet item
      </button>
    </li>
  )*/

  return (
    <div className={styles.container}>
      <Head>
        <title>Administrador de tareas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a el Administrador de tareas shidori
        </h1>
        <Link href="/proyecto">
          <a>
            ir a detalles de proyecto
          </a>
        </Link>
        <ul>
        {listadoProyectos.proyectos.map((proyecto) => (
        <li key={proyecto.id}>
          <Link href={`/proyecto/${encodeURIComponent(proyecto.id)}`}>
            <a>{proyecto.name}</a>
          </Link>
        </li>
      ))}
</ul>
      </main>
    </div>
  )
}

Home.getInitialProps = () => {
  const requestBody = {
    query: `
      query {
        proyectos {
          id
          name
          creationDate
          active
        }
      }
    `
  };
  return fetch('http://localhost:4000/graphql', {
    method: 'POST',
    body: JSON.stringify(requestBody),
    headers: {
      'Content-Type': 'application/json'
    }
  })
  .then(res => res.json())
  .then(response => {
    console.log(JSON.stringify(response.data))
    return { listadoProyectos: response.data }
  })
}
